######################################################################
# Automatically generated by qmake (3.1) Thu Jul 8 09:55:04 2021
######################################################################

TEMPLATE = app
TARGET = maliit-framework
INCLUDEPATH += .

# The following define makes your compiler warn you if you use any
# feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

# Input
HEADERS += connection/connectionfactory.h \
           connection/dbuscustomarguments.h \
           connection/dbusinputcontextconnection.h \
           connection/dbusserverconnection.h \
           connection/inputcontextdbusaddress.h \
           connection/mimserverconnection.h \
           connection/minputcontextconnection.h \
           connection/serverdbusaddress.h \
           connection/waylandinputmethodconnection.h \
           input-context/minputcontext.h \
           maliit-glib/maliitattributeextension.h \
           maliit-glib/maliitattributeextensionprivate.h \
           maliit-glib/maliitattributeextensionregistry.h \
           maliit-glib/maliitbus.h \
           maliit-glib/maliitbusprivate.h \
           maliit-glib/maliitinputmethod.h \
           maliit-glib/maliitpluginsettings.h \
           maliit-glib/maliitpluginsettingsprivate.h \
           maliit-glib/maliitsettingdata.h \
           maliit-glib/maliitsettingsentry.h \
           maliit-glib/maliitsettingsentryprivate.h \
           maliit-glib/maliitsettingsmanager.h \
           src/abstractplatform.h \
           src/mattributeextensionid.h \
           src/mattributeextensionmanager.h \
           src/mimhwkeyboardtracker.h \
           src/mimhwkeyboardtracker_p.h \
           src/mimonscreenplugins.h \
           src/mimpluginmanager.h \
           src/mimpluginmanager_p.h \
           src/mimserver.h \
           src/mimserveroptions.h \
           src/mimsettings.h \
           src/mimsettingsqsettings.h \
           src/mimsubviewoverride.h \
           src/minputmethodhost.h \
           src/msharedattributeextensionmanager.h \
           src/unknownplatform.h \
           src/waylandplatform.h \
           src/windowdata.h \
           src/windowgroup.h \
           src/xcbplatform.h \
           common/maliit/namespace.h \
           common/maliit/namespaceinternal.h \
           common/maliit/settingdata.h \
           src/maliit/standaloneinputmethod.h \
           src/maliit/standaloneinputmethodhost.h \
           src/quick/inputmethodquick.h \
           src/quick/inputmethodquickplugin.h \
           src/quick/keyoverridequick.h \
           src/quick/keyoverridequick_p.h \
           src/quick/maliitquick.h \
           tests/dummyimplugin/dummyimplugin.h \
           tests/dummyimplugin/dummyinputmethod.h \
           tests/dummyimplugin2/dummyimplugin2.h \
           tests/dummyimplugin3/dummyimplugin3.h \
           tests/dummyimplugin3/dummyinputmethod3.h \
           tests/dummyplugin/dummyplugin.h \
           tests/ft_exampleplugin/ft_exampleplugin.h \
           tests/ft_mimpluginmanager/ft_mimpluginmanager.h \
           tests/sanitychecks/sanitychecks.h \
           tests/stubs/fakeproperty.h \
           tests/stubs/mkeyboardstatetracker_stub.h \
           tests/ut_maliit_glib_settings/mockmaliitserver.h \
           tests/ut_mattributeextensionmanager/ut_mattributeextensionmanager.h \
           tests/ut_mimonscreenplugins/ut_mimonscreenplugins.h \
           tests/ut_mimpluginmanager/ut_mimpluginmanager.h \
           tests/ut_mimpluginmanagerconfig/ut_mimpluginmanagerconfig.h \
           tests/ut_mimserveroptions/ut_mimserveroptions.h \
           tests/ut_mimsettings/ut_mimsettings.h \
           tests/ut_minputmethodquickplugin/ut_minputmethodquickplugin.h \
           tests/ut_mkeyoverride/ut_mkeyoverride.h \
           tests/utils/core-utils.h \
           tests/utils/gui-utils.h \
           examples/apps/plainqt/mainwindow.h \
           src/maliit/plugins/abstractinputmethod.h \
           src/maliit/plugins/abstractinputmethodhost.h \
           src/maliit/plugins/abstractpluginsetting.h \
           src/maliit/plugins/attributeextension.h \
           src/maliit/plugins/attributeextension_p.h \
           src/maliit/plugins/extensionevent.h \
           src/maliit/plugins/extensionevent_p.h \
           src/maliit/plugins/inputmethodplugin.h \
           src/maliit/plugins/keyoverride.h \
           src/maliit/plugins/keyoverride_p.h \
           src/maliit/plugins/keyoverridedata.h \
           src/maliit/plugins/plugindescription.h \
           src/maliit/plugins/subviewdescription.h \
           src/maliit/plugins/updateevent.h \
           src/maliit/plugins/updateevent_p.h \
           src/maliit/plugins/updatereceiver.h \
           examples/plugins/cxx/helloworld/helloworldinputmethod.h \
           examples/plugins/cxx/helloworld/helloworldplugin.h \
           examples/plugins/cxx/override/overrideinputmethod.h \
           examples/plugins/cxx/override/overrideplugin.h \
           examples/plugins/qml/cyclekeys/cyclekeysplugin.h \
           examples/plugins/qml/override/overrideplugin.h \
           src/gtk/plugins/im-module/gtkimcontextwayland.h \
           src/qt/plugins/shellintegration/qwaylandinputpanelshellintegration.h \
           src/qt/plugins/shellintegration/qwaylandinputpanelsurface.h
SOURCES += connection/connectionfactory.cpp \
           connection/dbuscustomarguments.cpp \
           connection/dbusinputcontextconnection.cpp \
           connection/dbusserverconnection.cpp \
           connection/inputcontextdbusaddress.cpp \
           connection/mimserverconnection.cpp \
           connection/minputcontextconnection.cpp \
           connection/serverdbusaddress.cpp \
           connection/waylandinputmethodconnection.cpp \
           input-context/main.cpp \
           input-context/minputcontext.cpp \
           maliit-glib/maliitattributeextension.c \
           maliit-glib/maliitattributeextensionregistry.c \
           maliit-glib/maliitbus.c \
           maliit-glib/maliitinputmethod.c \
           maliit-glib/maliitpluginsettings.c \
           maliit-glib/maliitsettingdata.c \
           maliit-glib/maliitsettingsentry.c \
           maliit-glib/maliitsettingsmanager.c \
           passthroughserver/main.cpp \
           src/abstractplatform.cpp \
           src/mattributeextensionid.cpp \
           src/mattributeextensionmanager.cpp \
           src/mimhwkeyboardtracker.cpp \
           src/mimhwkeyboardtracker_stub.cpp \
           src/mimonscreenplugins.cpp \
           src/mimpluginmanager.cpp \
           src/mimserver.cpp \
           src/mimserveroptions.cpp \
           src/mimsettings.cpp \
           src/mimsettingsqsettings.cpp \
           src/mimsubviewoverride.cpp \
           src/minputmethodhost.cpp \
           src/msharedattributeextensionmanager.cpp \
           src/unknownplatform.cpp \
           src/waylandplatform.cpp \
           src/windowdata.cpp \
           src/windowgroup.cpp \
           src/xcbplatform.cpp \
           common/maliit/settingdata.cpp \
           src/maliit/standaloneinputmethod.cpp \
           src/maliit/standaloneinputmethodhost.cpp \
           src/quick/inputmethodquick.cpp \
           src/quick/inputmethodquickplugin.cpp \
           src/quick/keyoverridequick.cpp \
           tests/dummyimplugin/dummyimplugin.cpp \
           tests/dummyimplugin/dummyinputmethod.cpp \
           tests/dummyimplugin2/dummyimplugin2.cpp \
           tests/dummyimplugin3/dummyimplugin3.cpp \
           tests/dummyimplugin3/dummyinputmethod3.cpp \
           tests/dummyplugin/dummyplugin.cpp \
           tests/ft_exampleplugin/ft_exampleplugin.cpp \
           tests/ft_mimpluginmanager/ft_mimpluginmanager.cpp \
           tests/sanitychecks/sanitychecks.cpp \
           tests/stubs/fakeproperty.cpp \
           tests/ut_maliit_glib_settings/mockmaliitserver.c \
           tests/ut_maliit_glib_settings/ut_maliit_glib_settings.c \
           tests/ut_mattributeextensionmanager/ut_mattributeextensionmanager.cpp \
           tests/ut_mimonscreenplugins/ut_mimonscreenplugins.cpp \
           tests/ut_mimpluginmanager/ut_mimpluginmanager.cpp \
           tests/ut_mimpluginmanagerconfig/ut_mimpluginmanagerconfig.cpp \
           tests/ut_mimserveroptions/ut_mimserveroptions.cpp \
           tests/ut_mimsettings/ut_mimsettings.cpp \
           tests/ut_minputmethodquickplugin/ut_minputmethodquickplugin.cpp \
           tests/ut_mkeyoverride/ut_mkeyoverride.cpp \
           tests/utils/core-utils.cpp \
           tests/utils/gui-utils.cpp \
           examples/apps/plainqt/mainwindow.cpp \
           examples/apps/plainqt/plainqt.cpp \
           src/maliit/plugins/abstractinputmethod.cpp \
           src/maliit/plugins/abstractinputmethodhost.cpp \
           src/maliit/plugins/attributeextension.cpp \
           src/maliit/plugins/extensionevent.cpp \
           src/maliit/plugins/keyoverride.cpp \
           src/maliit/plugins/keyoverridedata.cpp \
           src/maliit/plugins/plugindescription.cpp \
           src/maliit/plugins/subviewdescription.cpp \
           src/maliit/plugins/updateevent.cpp \
           src/maliit/plugins/updatereceiver.cpp \
           examples/plugins/cxx/helloworld/helloworldinputmethod.cpp \
           examples/plugins/cxx/helloworld/helloworldplugin.cpp \
           examples/plugins/cxx/override/overrideinputmethod.cpp \
           examples/plugins/cxx/override/overrideplugin.cpp \
           examples/plugins/qml/cyclekeys/cyclekeysplugin.cpp \
           examples/plugins/qml/override/overrideplugin.cpp \
           src/gtk/plugins/im-module/gtkimcontextwayland.c \
           src/gtk/plugins/im-module/imwayland.c \
           src/qt/plugins/shellintegration/inputpanelshellplugin.cpp \
           src/qt/plugins/shellintegration/qwaylandinputpanelshellintegration.cpp \
           src/qt/plugins/shellintegration/qwaylandinputpanelsurface.cpp
RESOURCES += examples/plugins/qml/cyclekeys/cyclekeys.qrc \
             examples/plugins/qml/override/override.qrc
